<header class="wholesale-hero"><div><p class="eyebrow"><?= e(t('Wholesale / International')) ?></p><h1><?= t('Your market.<br><em>Our collection.</em>') ?></h1><p><?= e(t('A direct enquiry process for boutique owners, distributors and apparel buyers.')) ?></p></div><div class="wholesale-hero-image"><img src="<?= e(asset('images/editorial/shop_04.webp')) ?>" alt="Raspina Clothing wholesale collection" width="800" height="1050"><span><?= e(t('Enquiries / 2026')) ?></span></div></header>

<section class="wholesale-process section"><div class="section-heading"><p class="eyebrow"><?= e(t('A clear process')) ?></p><h2><?= e(t('From edit to quotation')) ?></h2></div><ol class="wholesale-steps"><li><span>01</span><h3><?= e(t('Build your shortlist')) ?></h3><p><?= e(t('Save products as you browse. Your list stays privately in this browser until you send it.')) ?></p><a href="<?= e(url('/shop')) ?>"><?= e(t('Explore the archive ↗')) ?></a></li><li><span>02</span><h3><?= e(t('Share the context')) ?></h3><p><?= e(t('Tell us your country, business, preferred quantities, sizing and timing.')) ?></p></li><li><span>03</span><h3><?= e(t('Receive a current quote')) ?></h3><p><?= e(t('We confirm availability, wholesale pricing, production options and delivery details.')) ?></p></li></ol></section>

<section class="wholesale-form-section" id="enquiry">
    <div class="wholesale-form-intro"><p class="eyebrow"><?= e(t('Start the enquiry')) ?></p><h2><?= t('Tell us about<br>your business.') ?></h2><p><?= e(t('No payment is taken here. This form starts a direct wholesale conversation with the Raspina team.')) ?></p><div class="shortlist-summary"><span><?= e(t('Inquiry shortlist')) ?></span><b><span data-shortlist-count>0</span> <?= e(t('saved pieces')) ?></b><a href="<?= e(url('/wishlist')) ?>"><?= e(t('Review list ↗')) ?></a></div></div>
    <div class="form-panel form-panel-dark">
        <?php if ($requested_product): ?><div class="requested-product"><span><?= e(t('Starting with')) ?></span><strong><?= e($requested_product['name']) ?></strong><small>SKU <?= e($requested_product['sku']) ?></small></div><?php endif; ?>
        <?php if ($form_flash): ?><div class="form-alert <?= $form_flash['ok'] ? 'is-success' : 'is-error' ?>" role="status"><?= e($form_flash['message']) ?></div><?php endif; ?>
        <form class="contact-form" method="post" action="<?= e(url('/wholesale')) ?>" data-inquiry-form>
            <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="product_slugs" value="<?= e($requested_product ? $requested_product['slug'] : '') ?>" data-product-slugs>
            <label class="honey" aria-hidden="true">Website<input type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true"></label>
            <div class="field-row"><label><span><?= e(t('Name *')) ?></span><input name="name" required maxlength="100" autocomplete="name"></label><label><span><?= e(t('Business name')) ?></span><input name="business_name" maxlength="120" autocomplete="organization"></label></div>
            <div class="field-row"><label><span><?= e(t('Business email *')) ?></span><input name="email" type="email" required maxlength="190" autocomplete="email"></label><label><span><?= e(t('Phone / WhatsApp')) ?></span><input name="phone" type="tel" maxlength="60" autocomplete="tel"></label></div>
            <label><span><?= e(t('Country / market')) ?></span><input name="country" maxlength="100" autocomplete="country-name"></label>
            <label><span><?= e(t('What do you need? *')) ?></span><textarea name="message" required minlength="10" maxlength="3000" rows="7" placeholder="<?= e(t('Tell us about quantities, categories, sizes, timing and destination…')) ?>"></textarea></label>
            <button class="button button-light" type="submit"><?= e(t('Send wholesale request ↗')) ?></button><p class="form-privacy"><?= t('We use these details only to respond to this enquiry. See <a href="/privacy">privacy</a>.') ?></p>
        </form>
    </div>
</section>
