<header class="admin-page-head compact-head">
    <div><p class="admin-eyebrow">Catalogue / live records</p><h1>Products <span class="head-count"><?= e($products['total'] ?? 0) ?></span></h1><p class="admin-lede">Shape the product archive buyers browse, save and quote.</p></div>
    <?php if ($admin_repository->isReady()): ?><a class="admin-primary-button" href="<?= e(admin_url('/products/new')) ?>">Add product <span aria-hidden="true">↗</span></a><?php endif; ?>
</header>
<?php if (!empty($admin_error)): ?><div class="admin-state-card <?= e($admin_repository->status()) ?>"><span class="state-dot"></span><div><strong>Catalogue status</strong><p><?= e($admin_error) ?></p></div></div><?php endif; ?>
<section class="admin-panel admin-table-panel">
    <div class="table-toolbar"><form class="admin-search" method="get" action="<?= e(admin_url('/products')) ?>"><label class="sr-only" for="product-search">Search products</label><input id="product-search" type="search" name="q" value="<?= e($query) ?>" placeholder="Search name, slug or SKU"><button type="submit">Search ↗</button></form><span class="toolbar-meta">Showing <?= e(count($products['items'] ?? array())) ?> of <?= e($products['total'] ?? 0) ?></span></div>
    <?php if (empty($products['items'])): ?><div class="empty-state table-empty"><span>▦</span><strong>No products found</strong><p>Try a different search or add the first catalogue record.</p></div>
    <?php else: ?><div class="admin-table-scroll"><table class="admin-table"><thead><tr><th>Product</th><th>SKU</th><th>Collection</th><th>Availability</th><th>Updated</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody><?php foreach ($products['items'] as $product): ?><tr><td><div class="table-primary"><a href="<?= e(admin_url('/products/edit/' . (int) $product['id'])) ?>"><?= e($product['name']) ?></a><?php if (!empty($product['featured'])): ?><span class="tiny-tag gold">Featured</span><?php endif; ?><small><?= e($product['slug']) ?></small></div></td><td class="mono-cell"><?= e($product['sku'] !== '' ? $product['sku'] : '—') ?></td><td><?= e($product['category_names'] ?: 'Unassigned') ?></td><td><span class="status-pill <?= e($product['stock_status']) ?>"><i></i><?= e(str_replace('onbackorder', 'back order', (string) $product['stock_status'])) ?></span><?php if ($product['stock_quantity'] !== null): ?><small class="stock-number"><?= e($product['stock_quantity']) ?> units</small><?php endif; ?></td><td><?= e($product['updated_at'] ? date('d M Y', strtotime($product['updated_at'])) : '—') ?></td><td><div class="table-actions"><a class="icon-action" href="<?= e(admin_url('/products/edit/' . (int) $product['id'])) ?>">Edit</a><form method="post" action="<?= e(admin_url('/products')) ?>" data-confirm="Delete this product? This cannot be undone."><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="admin_action" value="delete_product"><input type="hidden" name="id" value="<?= e($product['id']) ?>"><button class="icon-action danger" type="submit">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
    <?php if (($products['pages'] ?? 1) > 1): ?><nav class="admin-pagination" aria-label="Products pagination"><?php for ($page = 1; $page <= (int) $products['pages']; $page++): ?><a class="<?= $page === (int) $products['page'] ? 'is-current' : '' ?>" href="<?= e(admin_url('/products?' . http_build_query(array_filter(array('q' => $query, 'page' => $page))))) ?>"><?= e($page) ?></a><?php endfor; ?></nav><?php endif; ?>
</section>
