<?php
$disabled = !empty($read_only) ? 'disabled' : '';
$value = static function (string $key, $fallback = '') use ($form) { return $form[$key] ?? $fallback; };
$selectedCategories = array_map('intval', (array) ($form['category_ids'] ?? array()));
$productAction = !empty($form['id']) ? admin_url('/products/edit/' . (int) $form['id']) : admin_url('/products/new');
$apparelFields = array(
    'brand' => 'برند',
    'garment_type' => 'نوع لباس',
    'collection_name' => 'کالکشن',
    'season' => 'فصل / سال تولید',
    'fabric_composition' => 'جنس و ترکیب پارچه',
    'fabric_weight' => 'وزن پارچه',
    'color' => 'رنگ',
    'color_family' => 'طیف رنگی',
    'pattern' => 'طرح پارچه',
    'fit' => 'نوع تن‌خور (Fit)',
    'silhouette' => 'سیلوئت (فرم کلی لباس)',
    'neckline' => 'مدل یقه',
    'sleeve_length' => 'قد آستین',
    'garment_length' => 'قد لباس',
    'closure' => 'نحوه بسته‌شدن (دکمه/زیپ...)',
    'lining' => 'وضعیت آستر',
    'stretch' => 'میزان کشسانی پارچه',
    'origin_country' => 'کشور سازنده',
    'size_range' => 'محدوده سایزهای تولیدی'
);
?>
<header class="admin-page-head compact-head"><div><a class="admin-back-link" href="<?= e(admin_url('/products')) ?>">← بازگشت به محصولات</a><p class="admin-eyebrow">کاتالوگ / <?= !empty($form['id']) ? 'ویرایش رکورد محصول' : 'ثبت محصول جدید' ?></p><h1><?= !empty($form['id']) ? 'ویرایش محصول' : 'افزودن محصول جدید' ?></h1><p class="admin-lede">مشخصات ظاهری و جزئیات کاربردی لازم برای استعلام و سفارش خریداران عمده را در این بخش تکمیل کنید.</p></div></header>
<?php if (!empty($errors)): ?><div class="admin-alert error" role="alert"><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<?php if (!empty($read_only)): ?><div class="admin-state-card <?= e($admin_repository->status()) ?>" role="status"><span class="state-dot"></span><div><strong>وضعیت فقط خواندنی (بدون دیتابیس فعال)</strong><p><?= e($admin_repository->statusMessage()) ?></p></div></div><?php endif; ?>
<span id="product-form-errors" class="sr-only">لطفاً پیش از ذخیره‌سازی، هشدارهای اعتبارسنجی بالا را بررسی فرمایید.</span><form class="admin-editor-form" method="post" action="<?= e($productAction) ?>" aria-describedby="product-form-errors" enctype="multipart/form-data">
<input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= e($form['id'] ?? 0) ?>">
<div class="editor-layout"><div class="editor-main">
<section class="admin-panel editor-panel"><div class="panel-heading"><div><p class="admin-eyebrow">۰۱ / هویت و داستان محصول</p><h2>مشخصات پایه</h2></div></div><div class="form-grid">
<label class="span-2"><span>نام محصول <b>*</b></span><input type="text" name="name" value="<?= e($value('name')) ?>" maxlength="255" required <?= $disabled ?>></label><label><span>اسلاگ در آدرس اینترنتی (فقط انگلیسی) <b>*</b></span><input type="text" name="slug" value="<?= e($value('slug')) ?>" maxlength="120" pattern="[a-z0-9-]+" required aria-describedby="product-slug-help" <?= $disabled ?>><small id="product-slug-help">حروف کوچک انگلیسی، اعداد و خط تیره.</small></label><label><span>کد محصول (SKU) / شناسه مرجع</span><input type="text" name="sku" value="<?= e($value('sku')) ?>" maxlength="96" <?= $disabled ?>></label><label><span>نوع محصول</span><input type="text" name="product_type" value="<?= e($value('product_type', 'simple')) ?>" maxlength="50" <?= $disabled ?>></label><label><span>برند</span><input type="text" name="brand" value="<?= e($value('brand', 'Raspina')) ?>" maxlength="120" <?= $disabled ?>></label><label class="span-2"><span>خلاصه معرفی محصول</span><textarea name="summary" rows="3" maxlength="5000" <?= $disabled ?>><?= e($value('summary')) ?></textarea></label><label class="span-2"><span>توضیحات تکمیلی و کامل</span><textarea name="description" rows="8" maxlength="50000" <?= $disabled ?>><?= e($value('description')) ?></textarea></label></div></section>
<section class="admin-panel editor-panel"><div class="panel-heading"><div><p class="admin-eyebrow">۰۲ / مشخصات پوشاک</p><h2>نحوه تولید و دوخت</h2></div></div><div class="form-grid"><?php foreach ($apparelFields as $field => $label): ?><label><span><?= e($label) ?></span><input type="text" name="<?= e($field) ?>" value="<?= e($value($field)) ?>" maxlength="255" <?= $disabled ?>></label><?php endforeach; ?><label class="span-2"><span>دستورالعمل مراقبت و شستشو</span><textarea name="care_instructions" rows="3" maxlength="2000" <?= $disabled ?>><?= e($value('care_instructions')) ?></textarea></label><label class="toggle-field"><span>سایز سفارشی</span><input type="checkbox" name="customizable_size" value="1" <?= !empty($form['customizable_size']) ? 'checked' : '' ?> <?= $disabled ?>><strong>امکان دوخت با اندازه اختصاصی خریدار</strong></label><label class="toggle-field"><span>پارچه سفارشی</span><input type="checkbox" name="customizable_fabric" value="1" <?= !empty($form['customizable_fabric']) ? 'checked' : '' ?> <?= $disabled ?>><strong>امکان دوخت با پارچه انتخابی خریدار</strong></label></div></section>
<section class="admin-panel editor-panel"><div class="panel-heading"><div><p class="admin-eyebrow">۰۳ / اطلاعات عمده‌فروشی و موجودی</p><h2>بستر استعلام قیمت</h2></div></div><div class="form-grid"><label><span>واحد پولی</span><input type="text" name="currency" value="<?= e($value('currency', 'USD')) ?>" maxlength="3" pattern="[A-Za-z]{3}" <?= $disabled ?>></label><label><span>وضعیت انتشار</span><select name="publish_status" <?= $disabled ?>><option value="draft" <?= $value('publish_status') === 'draft' ? 'selected' : '' ?>>پیش‌نویس</option><option value="published" <?= $value('publish_status') === 'published' ? 'selected' : '' ?>>منتشر شده</option><option value="archived" <?= $value('publish_status') === 'archived' ? 'selected' : '' ?>>بایگانی شده</option></select></label><label><span>قیمت مرجع استعلام</span><input name="reference_price" inputmode="decimal" value="<?= e($value('reference_price')) ?>" <?= $disabled ?>></label><label><span>قیمت پایه (عادی)</span><input name="regular_price" inputmode="decimal" value="<?= e($value('regular_price')) ?>" <?= $disabled ?>></label><label><span>قیمت ویژه (تخفیف)</span><input name="sale_price" inputmode="decimal" value="<?= e($value('sale_price')) ?>" <?= $disabled ?>></label><label><span>وضعیت موجودی</span><select name="stock_status" <?= $disabled ?>><option value="instock" <?= $value('stock_status') === 'instock' ? 'selected' : '' ?>>موجود در انبار</option><option value="onbackorder" <?= $value('stock_status') === 'onbackorder' ? 'selected' : '' ?>>قابل پیش‌خرید</option><option value="outofstock" <?= $value('stock_status') === 'outofstock' ? 'selected' : '' ?>>ناموجود</option></select></label><label><span>تعداد موجودی انبار</span><input type="number" min="0" name="stock_quantity" value="<?= e($value('stock_quantity')) ?>" <?= $disabled ?>></label><label><span>حداقل تعداد سفارش عمده</span><input type="number" min="0" name="minimum_order_quantity" value="<?= e($value('minimum_order_quantity')) ?>" <?= $disabled ?>></label><label><span>زمان تحویل سفارش</span><input name="lead_time" value="<?= e($value('lead_time')) ?>" maxlength="120" placeholder="مثال: ۴ الی ۶ هفته" <?= $disabled ?>></label><label><span>تاریخ آماده عرضه</span><input type="date" name="available_from" value="<?= e($value('available_from')) ?>" <?= $disabled ?>></label><label class="toggle-field"><span>نمایش در صفحه اصلی</span><input type="checkbox" name="featured" value="1" <?= !empty($form['featured']) ? 'checked' : '' ?> <?= $disabled ?>><strong>در ردیف کارهای منتخب نمایش داده شود</strong></label><label class="span-2"><span>توضیح موجودی / عرضه</span><input name="availability_note" value="<?= e($value('availability_note')) ?>" maxlength="255" <?= $disabled ?>></label><label class="span-2"><span>یادداشت‌های عمده‌فروشی</span><textarea name="wholesale_notes" rows="4" maxlength="3000" <?= $disabled ?>><?= e($value('wholesale_notes')) ?></textarea></label></div></section>
<section class="admin-panel editor-panel"><div class="panel-heading"><div><p class="admin-eyebrow">۰۴ / سئو و جستجو</p><h2>دسترسی و یافت‌پذیری</h2></div></div><div class="form-grid"><label class="span-2"><span>دسته‌بندی‌ها</span><select name="categories[]" multiple size="7" aria-describedby="product-categories-help" <?= $disabled ?>><?php foreach ($categories as $category): ?><option value="<?= e($category['id']) ?>" <?= in_array((int) $category['id'], $selectedCategories, true) ? 'selected' : '' ?>><?= e($category['name']) ?> (<?= e($category['product_count']) ?>)</option><?php endforeach; ?></select><small id="product-categories-help">کلید Ctrl (یا Cmd در مک) را برای انتخاب همزمان چند مورد نگه دارید.</small></label><label class="span-2"><span>ویژگی‌های فرعی / هر ویژگی در یک سطر به فرمت «نام ویژگی: مقدار»</span><textarea name="attributes" rows="5" placeholder="مثال: آستر داخلی: دارد" <?= $disabled ?>><?= e(implode("\n", (array) ($form['attributes'] ?? array()))) ?></textarea></label><label><span>برچسب‌ها (با کاما تفکیک کنید)</span><textarea name="tags" rows="4" placeholder="مثال: جدید، بافت، سورمه‌ای" <?= $disabled ?>><?= e(implode(', ', (array) ($form['tags'] ?? array()))) ?></textarea></label><label><span>عنوان سئو (SEO Title)</span><input name="seo_title" value="<?= e($value('seo_title')) ?>" maxlength="255" <?= $disabled ?>></label><label class="span-2"><span>توضیحات سئو (SEO Description)</span><textarea name="seo_description" rows="3" maxlength="500" <?= $disabled ?>><?= e($value('seo_description')) ?></textarea></label></div></section>
<section class="admin-panel editor-panel"><div class="panel-heading"><div><p class="admin-eyebrow">۰۵ / متغیرها (Variants)</p><h2>ابعاد یا رنگ‌های متفاوت محصول</h2></div><button class="admin-light-button" type="button" data-add-variant <?= $disabled ?>>افزودن متغیر جدید</button></div><div class="variant-list" data-variant-list role="group" aria-describedby="product-variants-help"><?php foreach ((array) ($form['variants'] ?? array()) as $index => $variant): ?><div class="variant-row" data-variant-row><label><span>SKU</span><input name="variants[<?= (int) $index ?>][variant_sku]" value="<?= e($variant['variant_sku'] ?? '') ?>" <?= $disabled ?>></label><label><span>سایز</span><input name="variants[<?= (int) $index ?>][size]" value="<?= e($variant['size'] ?? '') ?>" <?= $disabled ?>></label><label><span>رنگ</span><input name="variants[<?= (int) $index ?>][color]" value="<?= e($variant['color'] ?? '') ?>" <?= $disabled ?>></label><label><span>تعداد</span><input type="number" min="0" name="variants[<?= (int) $index ?>][stock_quantity]" value="<?= e($variant['stock_quantity'] ?? '') ?>" <?= $disabled ?>></label><label><span>قیمت اختصاصی</span><input name="variants[<?= (int) $index ?>][price_override]" value="<?= e($variant['price_override'] ?? '') ?>" <?= $disabled ?>></label><label><span>وضعیت</span><select name="variants[<?= (int) $index ?>][stock_status]" <?= $disabled ?>><option value="instock" <?= ($variant['stock_status'] ?? '') === 'instock' ? 'selected' : '' ?>>موجود</option><option value="onbackorder" <?= ($variant['stock_status'] ?? '') === 'onbackorder' ? 'selected' : '' ?>>پیش‌خرید</option><option value="outofstock" <?= ($variant['stock_status'] ?? '') === 'outofstock' ? 'selected' : '' ?>>ناموجود</option></select></label><label class="toggle-field"><span>فعال</span><input type="checkbox" name="variants[<?= (int) $index ?>][is_active]" value="1" <?= !isset($variant['is_active']) || !empty($variant['is_active']) ? 'checked' : '' ?> <?= $disabled ?>></label><button type="button" class="icon-action danger" data-remove-variant>حذف</button></div><?php endforeach; ?></div><p id="product-variants-help" class="form-note">در صورتی که محصول سایز بندی و متغیر ندارد، این بخش را خالی بگذارید.</p></section>
</div><aside class="editor-aside"><section class="admin-panel editor-panel"><div class="panel-heading"><div><p class="admin-eyebrow">۰۶ / رسانه</p><h2>آرشیو تصاویر محصول</h2></div></div><?php if (!empty($can_upload)): ?><label><span>بارگذاری تصاویر محصول</span><input id="product-images-input" type="file" name="product_images[]" accept="image/jpeg,image/png,image/webp" multiple aria-describedby="product-images-help" <?= $disabled ?>><small id="product-images-help">فرمت‌های مجاز: JPEG, PNG یا WebP، حداکثر حجم مجاز ۸ مگابایت برای هر تصویر. حداکثر ۱۲ فایل.</small></label><label><span>متن جایگزین (Alt) برای تصاویر جدید</span><input id="product-upload-alt" type="text" name="upload_alt" maxlength="255" <?= $disabled ?>></label><?php endif; ?><label><span>مسیرهای محلی تصاویر</span><textarea name="images" rows="4" placeholder="/assets/images/catalog/..." aria-describedby="product-local-images-help" <?= $disabled ?>><?= e(implode("\n", (array) ($form['images'] ?? array()))) ?></textarea><small id="product-local-images-help">مسیرهای محلی وارد شده به صورت دستی پشتیبانی می‌شوند.</small></label><?php foreach ((array) ($form['image_records'] ?? array()) as $image): $path = (string) ($image['path'] ?? ''); if ($path === '') continue; $encoded = rawurlencode($path); ?><div class="existing-image"><input type="hidden" name="keep_images[]" value="<?= e($path) ?>"><strong><?= e(basename($path)) ?></strong><input type="text" name="image_alt[<?= e($encoded) ?>]" value="<?= e($image['alt_text'] ?? '') ?>" placeholder="متن جایگزین (Alt)" <?= $disabled ?>><label class="inline-check"><input type="radio" name="primary_image_path" value="<?= e($path) ?>" <?= ($form['primary_image_path'] ?? '') === $path ? 'checked' : '' ?> <?= $disabled ?>> تصویر اصلی</label><label class="inline-check"><input type="checkbox" name="remove_images[]" value="<?= e($path) ?>" <?= $disabled ?>> حذف</label></div><?php endforeach; ?></section><section class="admin-panel editor-panel"><div class="panel-heading"><div><p class="admin-eyebrow">نکات ویژه</p><h2>توجه خریدار</h2></div></div><p class="form-note">مشخصات را خلاصه، دقیق و واقعی بنویسید. این اطلاعات در صفحه محصول به خریداران عمده‌فروشی نمایش داده می‌شوند.</p></section></aside></div>
<?php if (empty($read_only)): ?><div class="editor-submit"><a class="admin-cancel-link" href="<?= e(admin_url('/products')) ?>">انصراف</a><button class="admin-primary-button" type="submit"><?= !empty($form['id']) ? 'ذخیره محصول' : 'ثبت محصول' ?> <span aria-hidden="true">→</span></button></div><?php endif; ?></form>
