<?php
$stockLabels = array(
    'instock' => 'موجود در انبار',
    'onbackorder' => 'قابل پیش‌خرید',
    'outofstock' => 'ناموجود',
);
?>
<header class="admin-page-head compact-head">
    <div><p class="admin-eyebrow">کاتالوگ / رکوردهای فعال</p><h1>محصولات <span class="head-count"><?= e($products['total'] ?? 0) ?></span></h1><p class="admin-lede">آرشیو محصولات را جهت مرور، ذخیره و ارسال درخواست خریداران شکل دهید.</p></div>
    <?php if ($admin_repository->isReady()): ?><a class="admin-primary-button" href="<?= e(admin_url('/products/new')) ?>">افزودن محصول <span aria-hidden="true">↗</span></a><?php endif; ?>
</header>
<?php if (!empty($admin_error)): ?><div class="admin-state-card <?= e($admin_repository->status()) ?>"><span class="state-dot"></span><div><strong>وضعیت کاتالوگ</strong><p><?= e($admin_error) ?></p></div></div><?php endif; ?>
<section class="admin-panel admin-table-panel">
    <div class="table-toolbar"><form class="admin-search" method="get" action="<?= e(admin_url('/products')) ?>"><label class="sr-only" for="product-search">جستجوی محصولات</label><input id="product-search" type="search" name="q" value="<?= e($query) ?>" placeholder="جستجو بر اساس نام، اسلاگ یا SKU"><button type="submit">جستجو ↗</button></form><span class="toolbar-meta">نمایش <?= e(count($products['items'] ?? array())) ?> از <?= e($products['total'] ?? 0) ?></span></div>
    <?php if (empty($products['items'])): ?><div class="empty-state table-empty"><span>▦</span><strong>هیچ محصولی پیدا نشد</strong><p>جستجوی دیگری را امتحان کنید یا اولین محصول کاتالوگ را اضافه کنید.</p></div>
    <?php else: ?><div class="admin-table-scroll"><table class="admin-table"><thead><tr><th>محصول</th><th>شناسه (SKU)</th><th>دسته‌بندی (کالکشن)</th><th>وضعیت موجودی</th><th>به‌روزرسانی</th><th><span class="sr-only">عملیات</span></th></tr></thead><tbody><?php foreach ($products['items'] as $product): ?><tr><td><div class="table-primary"><a href="<?= e(admin_url('/products/edit/' . (int) $product['id'])) ?>"><?= e($product['name']) ?></a><?php if (!empty($product['featured'])): ?><span class="tiny-tag gold">منتخب</span><?php endif; ?><small><?= e($product['slug']) ?></small></div></td><td class="mono-cell"><?= e($product['sku'] !== '' ? $product['sku'] : '—') ?></td><td><?= e($product['category_names'] ?: 'تخصیص‌نیافته') ?></td><td><span class="status-pill <?= e($product['stock_status']) ?>"><i></i><?= e($stockLabels[$product['stock_status']] ?? $product['stock_status']) ?></span><?php if ($product['stock_quantity'] !== null): ?><small class="stock-number"><?= e($product['stock_quantity']) ?> عدد</small><?php endif; ?></td><td><?= e($product['updated_at'] ? date('Y/m/d', strtotime($product['updated_at'])) : '—') ?></td><td><div class="table-actions"><a class="icon-action" href="<?= e(admin_url('/products/edit/' . (int) $product['id'])) ?>">ویرایش</a><form method="post" action="<?= e(admin_url('/products')) ?>" data-confirm="آیا از حذف این محصول اطمینان دارید؟ این عمل غیرقابل بازگشت است."><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="admin_action" value="delete_product"><input type="hidden" name="id" value="<?= e($product['id']) ?>"><button class="icon-action danger" type="submit">حذف</button></form></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
    <?php if (($products['pages'] ?? 1) > 1): ?><nav class="admin-pagination" aria-label="صفحات محصولات"><?php for ($page = 1; $page <= (int) $products['pages']; $page++): ?><a class="<?= $page === (int) $products['page'] ? 'is-current' : '' ?>" href="<?= e(admin_url('/products?' . http_build_query(array_filter(array('q' => $query, 'page' => $page))))) ?>"><?= e($page) ?></a><?php endfor; ?></nav><?php endif; ?>
</section>
