<?php
$roleMap = array(
    'Owner' => 'مالک سیستم',
    'owner' => 'مالک سیستم',
    'Manager' => 'مدیر عملیات',
    'manager' => 'مدیر عملیات',
    'Merchandiser' => 'مسئول کاتالوگ',
    'merchandiser' => 'مسئول کاتالوگ',
    'Viewer' => 'ناظر (فقط خواندنی)',
    'viewer' => 'ناظر (فقط خواندنی)',
);
?>
<header class="admin-page-head"><div><p class="admin-eyebrow">تیم / دسترسی‌ها</p><h1>کاربران سیستم</h1><p class="admin-lede">افرادی که به مدیریت کاتالوگ و عملیات آتلیه رسپینا کمک می‌کنند.</p></div><a class="admin-primary-button" href="<?= e(admin_url('/users/new')) ?>">افزودن کاربر جدید <span aria-hidden="true">→</span></a></header>
<?php if (!empty($admin_error)): ?><div class="admin-alert error" role="alert"><?= e($admin_error) ?></div><?php endif; ?>
<section class="admin-panel admin-table-panel"><div class="table-toolbar"><form class="admin-search" method="get" action="<?= e(admin_url('/users')) ?>"><label class="sr-only" for="user-search">جستجوی کاربران</label><input id="user-search" type="search" name="q" value="<?= e($query ?? '') ?>" placeholder="جستجوی نام، ایمیل یا نقش کاربر"><button type="submit">جستجو</button></form><span class="toolbar-meta"><?= count((array) $users) ?> عضو فعال</span></div><div class="admin-table-scroll"><table class="admin-table"><thead><tr><th>نام و مشخصات</th><th>نقش دسترسی</th><th>وضعیت</th><th>آخرین ورود</th><th><span class="sr-only">عملیات</span></th></tr></thead><tbody><?php foreach ((array) $users as $member): ?><tr><td class="table-primary" data-label="Name"><a href="<?= e(admin_url('/users/edit/' . (int) $member['id'])) ?>"><?= e($member['name']) ?></a><small><?= e($member['email']) ?><?= !empty($member['title']) ? ' / ' . e($member['title']) : '' ?></small></td><td data-label="Role"><?= e($roleMap[$member['role_title']] ?? $roleMap[$member['role']] ?? $member['role_title'] ?? $member['role'] ?? 'بدون نقش') ?></td><td data-label="Status"><span class="status-pill <?= !empty($member['is_active']) ? 'instock' : '' ?>"><i></i><?= !empty($member['is_active']) ? 'فعال' : 'غیرفعال' ?></span></td><td class="mono-cell" data-label="Last login"><?= !empty($member['last_login_at']) ? e($member['last_login_at']) : 'تاکنون وارد نشده' ?></td><td data-label="Actions"><div class="table-actions"><a class="icon-action" href="<?= e(admin_url('/users/edit/' . (int) $member['id'])) ?>">ویرایش</a><?php if ((int) $member['id'] !== (int) ($admin_user['id'] ?? 0)): ?><form method="post" action="<?= e(admin_url('/users')) ?>" data-confirm="آیا مطمئن هستید که می‌خواهید وضعیت این کاربر را تغییر دهید؟"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="admin_action" value="deactivate_user"><input type="hidden" name="id" value="<?= (int) $member['id'] ?>"><input type="hidden" name="active" value="<?= empty($member['is_active']) ? '1' : '0' ?>"><button class="icon-action danger" type="submit"><?= empty($member['is_active']) ? 'فعال‌سازی' : 'غیرفعال‌سازی' ?></button></form><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div><?php if (!$users): ?><div class="empty-state"><div><strong>هنوز هیچ عضو تیمی تعریف نشده است</strong><p>افرادی که به مدیریت و انتشار هر مجموعه کمک می‌کنند را دعوت کنید.</p></div></div><?php endif; ?></section>
